# Site settings
title: Hunter Winter Breaks
client:
  name: Hunter
  link: "https://www.hunterboots.com?utm_source=secretescapes&utm_medium=referral&utm_campaign=microsite&utm_term=coldcampaign19"
core-se-link: https://www.secretescapes.com/current-sales
description: >
  From Golden Circle adventures in Iceland to snowy Lakeland hikes in Cumbria, this collection brings you the best winter getaways we can find. Handpicked for you, match your winter escape with the right outerwear from Hunter. From snow boots to heat-insulated parkas, beat the cold in style as you set off on your winter adventure.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/hunter-winter-breaks" # the subpath of your site, e.g. /blog/
img:     "/hunter-winter-breaks/_assets/img"
css:     "/hunter-winter-breaks/_assets/css"
js:      "/hunter-winter-breaks/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed